import base64
import json
import logging

from odoo import _, api, fields, models

from ..lib import musicxml

_logger = logging.getLogger(__name__)


class MusicScore(models.Model):
    _name = "music.score"
    _description = "Musical Score"
    _order = "name, id"

    name = fields.Char(required=True, index="trigram")
    composer_id = fields.Many2one("res.partner", string="Composer")
    source_type = fields.Selection(
        [
            ("musicxml", "MusicXML"),
            ("midi", "MIDI"),
            ("pdf", "PDF (optical recognition)"),
        ],
        default="musicxml",
        required=True,
    )
    source_file = fields.Binary(string="Source File", attachment=True)
    source_filename = fields.Char()
    musicxml_file = fields.Binary(
        string="MusicXML",
        attachment=True,
        help="The score as MusicXML. For a MusicXML source this is the same "
             "file, uncompressed; for the other sources it is what the "
             "converter produced.",
    )
    musicxml_filename = fields.Char()
    state = fields.Selection(
        [
            ("draft", "Draft"),
            ("parsed", "Parsed"),
            ("ready", "Ready"),
            ("error", "Error"),
        ],
        default="draft",
        required=True,
        copy=False,
        index=True,
    )

    key_signature = fields.Char(readonly=True, copy=False)
    time_signature = fields.Char(readonly=True, copy=False)
    tempo_bpm = fields.Float(string="Tempo (BPM)", readonly=True, copy=False)
    duration_seconds = fields.Float(string="Duration (s)", readonly=True, copy=False)
    fermata_factor = fields.Float(
        default=musicxml.compiler.DEFAULT_FERMATA_FACTOR,
        help="How much longer a note under a fermata is held. 1.5 means half "
             "again its written length.",
    )

    parse_log = fields.Text(readonly=True, copy=False)
    warning_count = fields.Integer(readonly=True, copy=False)
    playback_json = fields.Text(
        readonly=True,
        copy=False,
        help="The compiled timeline the player reads. Regenerated by "
             "Recompile; never edited by hand.",
    )

    part_ids = fields.One2many("music.score.part", "score_id", string="Parts")
    note_ids = fields.One2many("music.note", "score_id", string="Notes")
    note_count = fields.Integer(compute="_compute_note_count", store=True)
    part_count = fields.Integer(compute="_compute_note_count", store=True)

    @api.depends("note_ids", "part_ids")
    def _compute_note_count(self):
        notes = dict(
            self.env["music.note"]._read_group(
                [("score_id", "in", self.ids)], ["score_id"], ["__count"]
            )
        )
        parts = dict(
            self.env["music.score.part"]._read_group(
                [("score_id", "in", self.ids)], ["score_id"], ["__count"]
            )
        )
        for score in self:
            score.note_count = notes.get(score, 0)
            score.part_count = parts.get(score, 0)

    # -- actions --------------------------------------------------------

    def action_parse(self):
        """Compile the source and store both the notes and the timeline."""
        for score in self:
            score._parse_one()
        return True

    def action_recompile(self):
        """Throw away what was compiled and do it again.

        Manual corrections to ``music.note`` are lost on purpose: the source
        file is the truth. Phase 3 will add an editing mode that recompiles
        from the notes instead.
        """
        return self.action_parse()

    def action_reset_to_draft(self):
        self._clear_compiled()
        self.write({"state": "draft", "parse_log": False, "warning_count": 0})
        return True

    def action_open_notes(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Notes of %s", self.name),
            "res_model": "music.note",
            "view_mode": "list,form",
            "domain": [("score_id", "=", self.id)],
            "context": {"default_score_id": self.id, "search_default_group_by_measure": 1},
        }

    # -- compilation ----------------------------------------------------

    def _parse_one(self):
        self.ensure_one()
        if not self.source_file:
            return self._fail(_("There is no source file to compile."))
        if self.source_type != "musicxml":
            return self._fail(
                _("%s sources are not supported yet; convert the score to "
                  "MusicXML first.", dict(self._fields["source_type"].selection)[self.source_type])
            )

        raw = base64.b64decode(self.source_file)
        log = musicxml.ParseLog()
        try:
            xml_bytes = musicxml.extract_musicxml(raw)
            compilation = musicxml.compile_musicxml(
                xml_bytes,
                options=musicxml.CompileOptions(fermata_factor=self.fermata_factor or 1.0),
                log=log,
            )
        except (musicxml.ContainerError, musicxml.UnsupportedScore) as exc:
            return self._fail(str(exc), log=log)
        except Exception as exc:  # noqa: BLE001 - a bad file must not 500
            _logger.exception("Compiling score %s failed", self.id)
            return self._fail(_("The score could not be compiled: %s", exc), log=log)

        self._clear_compiled()
        self._store_compilation(compilation)
        return True

    def _store_compilation(self, compilation):
        self.ensure_one()
        parts = self.env["music.score.part"].create([
            {
                "score_id": self.id,
                "external_id": part.id,
                "name": part.name,
                "instrument": part.instrument,
                "staff_count": part.staff_count,
                "midi_program": part.midi_program,
            }
            for part in compilation.parts
        ])
        part_by_external = {part.external_id: part.id for part in parts}

        # One create() with the whole list: a Chopin ballade is tens of
        # thousands of rows and a loop here would take minutes.
        self.env["music.note"].create([
            {
                "score_id": self.id,
                "part_id": part_by_external.get(note.part_id),
                "measure_number": _measure_number(note.measure_number),
                "voice": note.voice,
                "staff": note.staff,
                "hand": note.hand,
                "midi_number": note.midi,
                "pitch_step": note.step,
                "pitch_alter": note.alter,
                "pitch_octave": note.octave,
                "onset_ticks": note.onset_ticks,
                "duration_ticks": note.duration_ticks,
                "onset_seconds": note.onset_seconds,
                "duration_seconds": note.duration_seconds,
                "velocity": note.velocity,
                "is_tied_start": note.is_tied_start,
                "is_tied_stop": note.is_tied_stop,
                "is_grace": note.is_grace,
                "sustain_pedal": note.sustain_pedal,
            }
            for note in compilation.notes
        ])

        header = _(
            "%(notes)s notes, %(measures)s measures played, %(parts)s part(s).",
            notes=len(compilation.notes),
            measures=len(compilation.measures),
            parts=len(compilation.parts),
        )
        self.write({
            "state": "ready",
            "key_signature": compilation.key_signature,
            "time_signature": compilation.time_signature,
            "tempo_bpm": compilation.initial_tempo,
            "duration_seconds": compilation.duration_seconds,
            "playback_json": json.dumps(compilation.to_playback_dict()),
            "parse_log": "\n".join([header] + compilation.warnings),
            "warning_count": len(compilation.warnings),
            "musicxml_file": self.source_file,
            "musicxml_filename": self.source_filename,
        })

    def _clear_compiled(self):
        self.note_ids.unlink()
        self.part_ids.unlink()
        self.write({
            "playback_json": False,
            "key_signature": False,
            "time_signature": False,
            "tempo_bpm": 0.0,
            "duration_seconds": 0.0,
        })

    def _fail(self, message, log=None):
        self.ensure_one()
        lines = [message]
        if log is not None:
            lines += log.lines()
        self.write({
            "state": "error",
            "parse_log": "\n".join(lines),
            "warning_count": len(lines) - 1,
        })
        return False

    # -- playback -------------------------------------------------------

    def get_playback_data(self):
        """Timeline for the player. Never reads ``music.note`` row by row."""
        self.ensure_one()
        if not self.playback_json:
            return {}
        return json.loads(self.playback_json)


def _measure_number(raw):
    """Measure numbers are text in MusicXML ("12", "12a", "X1")."""
    digits = "".join(character for character in str(raw or "") if character.isdigit())
    return int(digits) if digits else 0
